export const ar = {
  // Header
  appTitle: 'سوق مزادي P2P',
  createAd: 'أنشئ إعلانًا',

  // Features
  'feature.react_shell.title': 'هيكل تطبيق React + TypeScript',
  'feature.react_shell.description': 'أساس تطبيق قوي وقابل للتطوير مبني باستخدام React 18 و TypeScript و Vite لتجربة تطوير حديثة.',
  'feature.ui_ux_system.title': 'نظام واجهة المستخدم وتجربة المستخدم',
  'feature.ui_ux_system.description': 'نظام تصميم ديناميكي يستخدم متغيرات CSS و Tailwind CSS. يدعم الوضعين الفاتح والداكن، ويتم حفظه في التخزين المحلي.',
  'feature.localization_system.title': 'نظام الترجمة (i18n)',
  'feature.localization_system.description': 'إعداد تدويل مرن يدعم لغات متعددة (الإنجليزية والعربية) مع اتجاه النص من اليمين إلى اليسار.',
  'feature.pwa_config.title': 'تكوين تطبيق الويب التقدمي (PWA)',
  'feature.pwa_config.description': 'جاهز لميزات تطبيق الويب التقدمي. يتضمن إعدادًا مبدئيًا لعامل الخدمة وبيان الويب للقدرات دون اتصال بالإنترنت.',
  'feature.user_registration.title': 'نظام تسجيل المستخدمين والملفات الشخصية',
  'feature.user_registration.description': 'مكونات الواجهة الأمامية وإدارة الحالة لتسجيل المستخدم وتسجيل الدخول ومعالجة الجلسات.',
  
  // P2P Network Engine Features
  'feature.p2p_node_server.title': 'خادم عقدة خفيف الوزن (Node.js/Rust)',
  'feature.p2p_node_server.description': 'عقدة P2P أساسية منفذة في خلفية عالية الأداء (مثل Node.js أو Rust) لمعالجة اتصالات الشبكة.',
  'feature.dht_discovery.title': 'تنفيذ DHT (طبقة الاكتشاف)',
  'feature.dht_discovery.description': 'جدول تجزئة موزع لاكتشاف الأقران، مما يسمح للعقد بالعثور على بعضها البعض بدون خوادم مركزية.',
  'feature.bootstrap_nodes.title': 'تكوين عقد التمهيد',
  'feature.bootstrap_nodes.description': 'عقد أولية ومستقرة يتصل بها الأقران الجدد من أجل الانضمام إلى شبكة P2P.',
  'feature.data_sync.title': 'مزامنة البيانات وحل التعارضات',
  'feature.data_sync.description': 'آليات لمزامنة الحالة عبر العقد وحل تعارضات البيانات في بيئة موزعة.',
  'feature.tls_security.title': 'طبقة أمان TLS من طرف إلى طرف',
  'feature.tls_security.description': 'ضمان تشفير جميع الاتصالات من نظير إلى نظير وتأمينها باستخدام أمان طبقة النقل (TLS).',

  // Data & Local Storage System
  'feature.local_database.title': 'قاعدة بيانات محلية (SQLite/Realm)',
  'feature.local_database.description': 'قاعدة بيانات محلية مدمجة وفعالة لتخزين البيانات دون اتصال بالإنترنت وقدرات استعلام معقدة.',
  'feature.media_management.title': 'إدارة الوسائط (صور/فيديو)',
  'feature.media_management.description': 'نظام لمعالجة وتخزين واسترجاع ملفات الوسائط المحلية مثل الصور ومقاطع الفيديو بكفاءة.',
  'feature.metadata_sync.title': 'مزامنة البيانات الوصفية',
  'feature.metadata_sync.description': 'ضمان أن البيانات الوصفية للملفات المحلية تظل محدثة مع شبكة P2P.',
  'feature.cache_management.title': 'استراتيجية إدارة ذاكرة التخزين المؤقت',
  'feature.cache_management.description': 'سياسات تخزين مؤقت ذكية (مثل LRU) لإدارة التخزين وضمان الوصول السريع إلى البيانات المستخدمة بشكل متكرر.',
  'feature.media_compression.title': 'ضغط الوسائط (WebP/AVIF)',
  'feature.media_compression.description': 'ضغط الوسائط الفوري إلى تنسيقات حديثة مثل WebP و AVIF لتوفير المساحة وعرض النطاق الترددي.',

  // Main Application UI
  'feature.marketplace.title': 'واجهة السوق',
  'feature.marketplace.description': 'واجهة مستخدم للسوق تعمل بكامل طاقتها، قائمة على المكونات لتصفح وعرض العناصر.',
  'feature.search_discovery.title': 'نظام البحث والاستكشاف',
  'feature.search_discovery.description': 'قدرات بحث متقدمة مع تصفية وفرز ومحرك توصيات لتعزيز اكتشاف المستخدم.',
  'feature.profile_management.title': 'إدارة الملف الشخصي',
  'feature.profile_management.description': 'أقسام شاملة لملف المستخدم لإدارة المعلومات الشخصية والإعدادات والتفاصيل العامة.',
  'feature.wallet_transactions.title': 'المحفظة والمعاملات',
  'feature.wallet_transactions.description': 'واجهة محفظة آمنة لإدارة الأرصدة وعرض سجل المعاملات ومعالجة المدفوعات.',
  'feature.bottom_nav_routing.title': 'التنقل السفلي والتوجيه',
  'feature.bottom_nav_routing.description': 'نظام تنقل سفلي بديهي ومناسب للجوال مع موجه قوي من جانب العميل لانتقالات سلسة بين الصفحات.',

  // Data Transfer & Communication
  'feature.api_integration.title': 'واجهات برمجة التطبيقات (REST/WebSocket)',
  'feature.api_integration.description': 'تكامل قوي مع خدمات الواجهة الخلفية باستخدام واجهات برمجة تطبيقات REST للطلبات القياسية و WebSockets للاتصال ثنائي الاتجاه في الوقت الفعلي.',
  'feature.chunked_transfer.title': 'نقل البيانات المقسم',
  'feature.chunked_transfer.description': 'يتعامل بكفاءة مع عمليات نقل الملفات الكبيرة عن طريق تقسيمها إلى أجزاء أصغر يمكن التحكم فيها، مع دعم للإيقاف المؤقت والاستئناف.',
  'feature.lazy_loading.title': 'التحميل الكسول للصور',
  'feature.lazy_loading.description': 'يحسن أداء تحميل الصفحة الأولي عن طريق تأجيل تحميل الصور خارج الشاشة حتى تكون هناك حاجة إليها.',
  'feature.real_time_messaging.title': 'المراسلة في الوقت الفعلي',
  'feature.real_time_messaging.description': 'نظام مراسلة فوري قابل للتطوير للتواصل الفوري بين المستخدمين، مبني على WebSockets.',
  'feature.performance_optimization.title': 'تحسين الأداء',
  'feature.performance_optimization.description': 'تقنيات متقدمة مثل تقسيم الكود، والتخلص من التعليمات البرمجية غير المستخدمة، وتنظيم الطلبات لضمان تجربة مستخدم سريعة وسلسة.',

  // Offline & Sync System
  'feature.offline_first.title': 'بنية "الأوفلاين أولاً"',
  'feature.offline_first.description': 'مصمم للعمل بسلاسة دون اتصال بالإنترنت، مما يضمن أن الوظائف الأساسية متاحة دائمًا، مع مزامنة البيانات عند استعادة الاتصال.',
  'feature.background_sync.title': 'المزامنة في الخلفية',
  'feature.background_sync.description': 'مزامنة تلقائية للبيانات في الخلفية، للحفاظ على تطابق البيانات المحلية والبعيدة دون مقاطعة المستخدم.',
  'feature.conflict_resolution.title': 'حل التعارضات (ساعات المتجهات)',
  'feature.conflict_resolution.description': 'حل متقدم للتعارضات باستخدام ساعات المتجهات لدمج تغييرات البيانات من عقد مختلفة دون فقدان البيانات.',
  'feature.push_notifications.title': 'الإشعارات الفورية',
  'feature.push_notifications.description': 'إشعارات فورية في الوقت الفعلي لإبقاء المستخدمين متفاعلين ومطلعين على التحديثات المهمة، حتى عند إغلاق التطبيق.',
  'feature.local_notifications.title': 'التنبيهات والإشعارات المحلية',
  'feature.local_notifications.description': 'جدولة وتشغيل الإشعارات المحلية للتذكيرات والتنبيهات والأحداث الحساسة للوق-ت مباشرة على الجهاز.',

  // Testing & Quality Assurance
  'feature.unit_tests.title': 'اختبارات الوحدة (Jest)',
  'feature.unit_tests.description': 'اختبارات وحدة شاملة للمكونات والوظائف الفردية باستخدام Jest ومكتبة اختبار React لضمان موثوقية الكود.',
  'feature.integration_tests.title': 'الاختبارات التكاملية (شبكة P2P)',
  'feature.integration_tests.description': 'اختبارات متخصصة للتحقق من التفاعلات وتدفق البيانات بين عقد شبكة P2P المختلفة ومكونات النظام.',
  'feature.e2e_tests.title': 'اختبارات E2E (Cypress)',
  'feature.e2e_tests.description': 'اختبارات شاملة تحاكي سيناريوهات المستخدم الحقيقية مع Cypress للتحقق من وظائف التطبيق من منظور المستخدم.',
  'feature.performance_testing.title': 'اختبار الأداء',
  'feature.performance_testing.description': 'اختبارات التحميل والإجهاد لقياس استجابة التطبيق وقابليته للتوسع واستخدامه للموارد في ظل ظروف مختلفة.',
  'feature.security_auditing.title': 'التدقيق الأمني',
  'feature.security_auditing.description': 'عمليات تدقيق أمني منتظمة ومسح للثغرات لتحديد وتخفيف التهديدات المحتملة، وضمان سلامة البيانات وخصوصية المستخدم.',

  // Deployment & Distribution
  'feature.app_store_deployment.title': 'النشر على متجر التطبيقات',
  'feature.app_store_deployment.description': 'عملية مبسطة لتغليف ونشر التطبيق على متجر تطبيقات Apple، بما في ذلك إدارة البيانات الوصفية والأصول.',
  'feature.play_store_deployment.title': 'النشر على متجر Play',
  'feature.play_store_deployment.description': 'خط أنابيب بناء وإصدار آلي لنشر التطبيق على متجر Google Play لأجهزة Android.',
  'feature.web_pwa.title': 'نسخة الويب (PWA)',
  'feature.web_pwa.description': 'تطبيق ويب تقدمي كامل الميزات للوصول الفوري عبر الويب، مع إمكانيات العمل دون اتصال ووظيفة التثبيت على الشاشة الرئيسية.',
  'feature.update_mechanism.title': 'آلية التحديث',
  'feature.update_mechanism.description': 'نظام تحديث سلس عبر الهواء لتقديم ميزات جديدة وإصلاحات للأخطاء للمستخدمين دون الحاجة إلى تحديث كامل من متجر التطبيقات.',
  'feature.analytics_monitoring.title': 'التحليلات والمراقبة',
  'feature.analytics_monitoring.description': 'التكامل مع أدوات التحليلات ومراقبة الأداء لتتبع الاستخدام والإبلاغ عن الأعطال وتحسين تجربة المستخدم.',

  // Status
  'status.complete': 'مكتمل',
  'status.in_progress': 'قيد التنفيذ',
  'status.active': 'نشط',
  'status.banned': 'محظور',

  // ARIA Labels
  'aria.toggle_theme': 'تبديل السمة',
  'aria.toggle_language': 'تبديل اللغة',
  'aria.logout': 'تسجيل الخروج',
  'aria.open_admin_panel': 'فتح لوحة تحكم المسؤول',
  'aria.close_admin_panel': 'إغلاق لوحة تحكم المسؤول',
  'aria.go_back': 'العودة للخلف',
  'aria.open_marketplace_admin_panel': 'فتح لوحة تحكم مسؤول السوق',
  'aria.like_ad': 'إعجاب بالإعلان',
  'aria.edit_ad': 'تعديل الإعلان',

  // --- Start of New Auth System Translations ---
  // Auth Page
  'auth.login_title': 'تسجيل الدخول إلى مزادي',
  'auth.register_title': 'انضم إلى مزادي',
  'auth.welcome_message': 'سوق P2P',
  'auth.username': 'اسم المستخدم',
  'auth.email': 'عنوان البريد الإلكتروني',
  'auth.phone': 'رقم الهاتف',
  'auth.password': 'كلمة المرور',
  'auth.confirm_password': 'تأكيد كلمة المرور',
  'auth.login_button': 'تسجيل الدخول',
  'auth.register_button': 'إنشاء حساب',
  'auth.guest_button': 'المتابعة كزائر',
  'auth.go_to_register': "ليس لديك حساب؟",
  'auth.go_to_register_link': 'أنشئ حسابًا',
  'auth.go_to_login': 'هل لديك حساب بالفعل؟',
  'auth.go_to_login_link': 'سجل الدخول',
  'auth.welcome_back': 'مرحبًا بعودتك',
  'auth.remember_me': 'تذكرني',
  'auth.forgot_password': 'هل نسيت كلمة المرور؟',
  'auth.social_login_divider': 'أو المتابعة باستخدام',
  'auth.terms_agree': 'أوافق على',
  'auth.terms_and_conditions': 'الشروط والأحكام',
  'auth.logout': 'تسجيل الخروج',

  'auth.forgot_password_title': 'إعادة تعيين كلمة المرور',
  'auth.forgot_password_prompt': 'أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور.',
  'auth.send_reset_link': 'إرسال رابط إعادة التعيين',
  'auth.reset_link_sent': 'إذا كان هناك حساب بهذا البريد الإلكتروني، فقد أرسلنا رابط إعادة تعيين كلمة المرور إليه.',

  'auth.registration.title': 'تسجيل',
  'auth.registration.message': 'سجل الآن واحصل على وصول كامل لتطبيقنا.',
  'auth.registration.firstname': 'الاسم الأول',
  'auth.registration.lastname': 'اسم العائلة',
  'auth.registration.submit': 'إرسال',
  'auth.registration.submitting': 'جارٍ الإرسال...',


  // Social Buttons
  'auth.method.google': 'تسجيل الدخول باستخدام Google',
  'auth.method.facebook': 'تسجيل الدخول باستخدام Facebook',
  'auth.method.twitter': 'تسجيل الدخول باستخدام Twitter',
  'auth.method.apple': 'تسجيل الدخول باستخدام Apple',
  'auth.method.github': 'تسجيل الدخول باستخدام GitHub',
  'auth.method.phone': 'تسجيل الدخول باستخدام الهاتف',

  // Password Strength
  'auth.password_strength.too_weak': 'ضعيفة جدًا',
  'auth.password_strength.weak': 'ضعيفة',
  'auth.password_strength.medium': 'متوسطة',
  'auth.password_strength.strong': 'قوية',
  
  // Selectors
  'auth.select_language': 'اختر اللغة',
  'auth.select_country': 'اختر الدولة',

  // Phone Verification
  'auth.phone_verification_title': 'تحقق من رقم هاتفك',
  'auth.enter_phone_prompt': 'أدخل رقم هاتفك لتلقي رمز التحقق.',
  'auth.send_code': 'أرسل الرمز',
  'auth.enter_code_prompt': 'أدخل الرمز المكون من 6 أرقام الذي أرسلناه إلى هاتفك.',
  'auth.verification_code': 'رمز التحقق',
  'auth.verify': 'تحقق',
  'auth.resend_code': 'إعادة إرسال الرمز',
  'auth.back_to_login': 'العودة إلى تسجيل الدخول',
  'auth.error_invalid_code': 'رمز التحقق غير صالح.',
  
  // 2FA Verification
  'auth.2fa_title': 'المصادقة الثنائية',
  'auth.2fa_prompt': 'تم إرسال رمز التحقق إلى تطبيق المصادقة الخاص بك.',
  'auth.2fa_enter_code': 'أدخل الرمز المكون من 6 أرقام',

  // OAuth Handler
  'auth.oauth_redirect_title': 'جارٍ الاتصال...',
  'auth.oauth_redirect_message': 'جارٍ إعادة توجيهك إلى {provider} للمصادقة. يرجى الانتظار.',
  'auth.connecting_to': 'جارٍ الاتصال بـ {provider}...',
  'auth.error_oauth_failed': 'فشل الاتصال بـ {provider}. يرجى المحاولة مرة أخرى.',
  'auth.try_again': 'حاول مرة أخرى',

  // Errors
  'auth.error_invalid_credentials': 'البريد الإلكتروني أو كلمة المرور غير صالحة.',
  'auth.error_generic': 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
  'auth.error_user_exists': 'يوجد مستخدم بهذا البريد الإلكتروني بالفعل.',
  'auth.error_password_mismatch': "كلمتا المرور غير متطابقتين.",
  'auth.error_invalid_email': 'يرجى إدخال عنوان بريد إلكتروني صالح.',
  'auth.error_username_short': 'يجب أن يكون اسم المستخدم 3 أحرف على الأقل.',
  'auth.error_phone_invalid': 'يرجى إدخال رقم هاتف صالح.',
  'auth.error_terms_required': 'يجب عليك قبول الشروط والأحكام.',
  'auth.error_field_required': 'هذا الحقل مطلوب.',
  'auth.error_account_locked': 'محاولات تسجيل دخول فاشلة كثيرة جدًا. تم قفل حسابك لمدة 60 ثانية.',
  'auth.error_session_expired': 'انتهت صلاحية جلستك. يرجى تسجيل الدخول مرة أخرى.',
  'auth.error_account_suspended': 'تم تعليق هذا الحساب.',

  // Admin Panel
  'admin.title': 'عناصر تحكم المسؤول',
  'admin.admin_section': 'قسم المسؤول',
  'admin.edit': 'تعديل',
  'admin.done': 'تم',
  'admin.enabled_methods': 'طرق تسجيل الدخول الممكنة',
  'admin.visible_elements': 'عناصر واجهة المستخدم المرئية',
  'admin.color_scheme': 'نظام الألوان',
  'admin.primary': 'الأساسي',
  'admin.background': 'الخلفية',
  'admin.text': 'النص',
  'admin.button': 'الزر',
  'admin.button_text': 'نص الزر',
  'admin.border': 'الإطار',
  'admin.custom_css': 'CSS مخصص',
  'admin.dashboard_title': 'لوحة تحكم المسؤول',
  'admin.user_tiers_config': 'فئات المستخدمين',
  'admin.tier_benefits': 'المزايا',
  'admin.tier_requirements': 'المتطلبات',
  'admin.max_ads': 'الحد الأقصى للإعلانات',
  'admin.image_slots': 'عدد الصور',
  'admin.min_transactions': 'الحد الأدنى للمعاملات',
  'admin.min_rating': 'الحد الأدنى للتقييم',
  'admin.save_changes': 'حفظ التغييرات',
  'admin.save_success': 'تم حفظ الإعدادات!',
  'admin.user_tiers_updated_success': 'تم تحديث فئات المستخدمين بنجاح!',
  'admin.system_config_saved_success': 'تم حفظ إعدادات النظام!',
  'admin.user_management': 'إدارة المستخدمين',
  'admin.ad_management': 'إدارة الإعلانات',
  'admin.moderation_queue': 'قائمة انتظار الإشراف',
  'admin.moderation_queue_empty': 'قائمة انتظار الإشراف فارغة.',
  'admin.activity_log': 'سجل النشاط',
  'admin.system_config': 'إعدادات النظام',
  'admin.search_users': 'ابحث عن مستخدمين بالاسم أو البريد الإلكتروني...',
  'admin.search_ads': 'ابحث عن إعلانات بالعنوان...',
  'admin.user': 'المستخدم',
  'admin.status': 'الحالة',
  'admin.tier': 'الفئة',
  'admin.ip_address': 'عنوان IP',
  'admin.actions': 'الإجراءات',
  'admin.ad_title': 'عنوان الإعلان',
  'admin.seller': 'البائع',
  'admin.reports': 'البلاغات',
  'admin.reason': 'السبب (الأسباب)',
  'admin.approve': 'موافقة',
  'admin.remove': 'إزالة',
  'admin.select_all': 'تحديد الكل',
  'admin.bulk_actions': 'إجراءات جماعية',
  'admin.ban_selected': 'حظر المحددين',
  'admin.unban_selected': 'إلغاء حظر المحددين',
  'admin.remove_selected': 'إزالة المحدد',
  'admin.log_event': 'الحدث',
  'admin.log_details': 'التفاصيل',
  'admin.log_timestamp': 'الوقت',
  'admin.log.user_registered': 'تسجيل مستخدم جديد',
  'admin.log.ad_posted': 'نشر إعلان جديد',
  'admin.log.user_login': 'تسجيل دخول مستخدم',
  'admin.config.site_maintenance': 'صيانة الموقع',
  'admin.config.maintenance_enabled': 'تفعيل وضع الصيانة',
  'admin.config.registration_open': 'تسجيل المستخدمين',
  'admin.config.registration_enabled': 'السماح بالتسجيلات الجديدة',
  'admin.config.commission_rates': 'معدلات العمولة (٪)',
  'admin.config.content_moderation': 'استراتيجية الإشراف على المحتوى',
  'admin.config.moderation.auto': 'تلقائي',
  'admin.config.moderation.manual': 'يدوي',
  'admin.config.moderation.hybrid': 'مختلط',
  'admin.config.payment_methods': 'طرق الدفع الممكنة',
  'admin.config.payment.credit_card': 'بطاقة الائتمان',
  'admin.config.payment.paypal': 'PayPal',
  'admin.config.payment.crypto': 'عملات مشفرة',
  'admin.config.payment.bank_transfer': 'تحويل بنكي',
  'admin.analytics': 'التحليلات',
  'admin.total_users': 'إجمالي المستخدمين',
  'admin.total_active_ads': 'إجمالي الإعلانات النشطة',
  'admin.est_total_revenue': 'إجمالي الإيرادات المقدرة',
  'admin.user_growth': 'نمو المستخدمين',
  'admin.revenue_by_tier': 'الإيرادات المقدرة حسب الفئة',
  'admin.ads_by_category': 'أداء المحتوى (الإعلانات حسب الفئة)',
  'admin.ads_by_country': 'التوزيع الجغرافي (الإعلانات حسب البلد)',
  'admin.system_health': 'مراقبة صحة النظام',
  'admin.avg_response': 'متوسط استجابة API',
  'admin.server_load': 'تحميل الخادم',
  'admin.ban_prompt': 'أدخل سبب حظر {name}:',
  'admin.unban_confirm': 'هل أنت متأكد أنك تريد إلغاء حظر {name}؟',
  'admin.bulk_ban_prompt': 'أدخل سبب حظر المستخدمين المحددين:',
  'admin.remove_ad_prompt': 'أدخل سبب إزالة "{title}":',
  'admin.bulk_remove_ad_prompt': 'أدخل سبب إزالة الإعلانات المحددة:',
  
  // Marketplace
  'marketplace.title': 'استكشف القوائم',
  'marketplace.search_placeholder': 'ابحث عن أي شيء...',
  'ad.posted_by': 'نشر بواسطة',
  'ad.seller_info': "معلومات البائع",
  'ad.details': 'التفاصيل',
  'ad.condition': 'الحالة',
  'ad.quantity': 'الكمية',
  'ad.category': 'الفئة',
  'ad.location': 'الموقع',
  'ad.description': 'الوصف',
  'ad.specifications': 'المواصفات',
  'ad.delivery_info': 'معلومات التوصيل',
  'ad.delivery_type': 'نوع التوصيل',
  'ad.delivery_time': 'وقت التسليم المقدر',
  'ad.delivery_cost': 'تكلفة التوصيل',
  'ad.video_preview': 'معاينة الفيديو',
  'ad.document_preview': 'معاينة المستند',
  
  // Ad Creation
  'ad.create.title': 'إنشاء إعلان جديد',
  'ad.create.step1': 'التفاصيل',
  'ad.create.step2': 'الوسائط',
  'ad.create.step3': 'التوصيل',
  'ad.create.step4': 'مراجعة',
  'ad.create.next_step': 'الخطوة التالية',
  'ad.create.prev_step': 'الخطوة السابقة',
  'ad.create.post_ad': 'نشر الإعلان',
  'ad.create.title_label': 'عنوان الإعلان',
  'ad.create.description_label': 'الوصف',
  'ad.create.price_label': 'السعر',
  'ad.create.category_label': 'الفئة',
  'ad.create.condition_label': 'الحالة',
  'ad.create.quantity_label': 'الكمية',
  'ad.create.condition_new': 'جديد',
  'ad.create.condition_used': 'مستعمل',
  'ad.create.condition_refurbished': 'مجدد',
  'ad.create.cancel': 'إلغاء',
  'ad.create.cancel_confirm': 'هل أنت متأكد أنك تريد الإلغاء؟ سيتم مسح مسودتك.',
  'ad.create.error': 'فشل إنشاء الإعلان. يرجى المحاولة مرة أخرى.',
  'ad.create.select_category': 'اختر الفئة',
  'ad.create.media_title': 'تحميل الوسائط',
  'ad.create.media_prompt': 'أضف صورًا أو مقاطع فيديو أو مستندات لإبراز إعلانك.',
  'ad.create.add_photos': 'إضافة صور',
  'ad.create.add_video': 'إضافة فيديو',
  'ad.create.add_document': 'إضافة مستند',
  'ad.create.upload_photos': 'تحميل الصور',
  'ad.create.upload_video': 'تحميل الفيديو',
  'ad.create.upload_document': 'تحميل المستند',
  'ad.create.video_url_placeholder': 'https://www.youtube.com/watch?v=...',
  'ad.create.video_url_label': 'رابط الفيديو (مثل يوتيوب)',
  'ad.create.doc_name_label': 'اسم المستند',
  'ad.create.doc_name_placeholder': 'مثال: دليل المنتج',
  'ad.create.doc_url_label': 'رابط المستند',
  'ad.create.doc_url_placeholder': 'https://...',
  'ad.create.review_title': 'مراجعة إعلانك',
  'ad.create.limit_reached_title': 'تم الوصول إلى حد الإعلانات',
  'ad.create.limit_reached_message': 'لقد نشرت {adCount} من {limit} إعلانًا مسموحًا به لفئة {tier} الخاصة بك.',
  'ad.create.limit_reached_suggestion': 'لنشر المزيد من الإعلانات، يرجى ترقية فئة حسابك.',
  'ad.create.back_to_marketplace': 'العودة إلى السوق',

  // Social
  'social.like': 'إعجاب',
  'social.save': 'حفظ',
  'social.share': 'مشاركة',
  'social.comments_section': 'التعليقات',
  'social.reviews_section': 'التقييمات والمراجعات',
  'social.add_comment_placeholder': 'أضف تعليقًا...',
  'social.add_comment_button': 'نشر',
  'social.no_comments': 'لا توجد تعليقات حتى الآن.',
  'social.no_reviews': 'لا توجد مراجعات حتى الآن.',
  'social.rate_this_ad': 'قيم هذا العنصر',
  'social.your_rating': 'تقييمك',
  'social.your_review': 'مراجعتك',
  'social.submit_review': 'إرسال المراجعة',
  'social.reply': 'رد',

  // Profile
  'profile.title': 'الملف الشخصي',
  'profile.settings': 'الإعدادات',
  'profile.language_region': 'اللغة والمنطقة',
  'profile.cloud_sync_title': 'إعدادات المزامنة السحابية',
  'profile.member_since': 'عضو منذ',
  'profile.bio': 'السيرة الذاتية',
  'profile.reputation': 'السمعة',
  'profile.overall_rating': 'التقييم العام',
  'profile.reviews': 'المراجعات',
  'profile.active_ads': 'الإعلانات النشطة',
  'profile.my_ads': 'إعلاناتي',
  'profile.verified': 'موثق',
  'profile.user_not_found': 'لم يتم العثور على المستخدم.',
  'profile.no_active_ads': 'لا يوجد لدى هذا المستخدم إعلانات نشطة.',
  
  // Cloud Sync
  'cloud.connect_provider': 'ربط التخزين السحابي',
  'cloud.provider.google-drive': 'ربط Google Drive',
  'cloud.provider.dropbox': 'ربط Dropbox',
  'cloud.connected_as': 'متصل كـ {email}',
  'cloud.disconnect': 'قطع الاتصال',
  'cloud.settings': 'إعدادات المزامنة',
  'cloud.enable_sync': 'تفعيل المزامنة التلقائية',
  'cloud.wifi_only': 'المزامنة عبر Wi-Fi فقط',
  'cloud.media_compression': 'ضغط الوسائط',
  'cloud.compression.none': 'بدون (الجودة الأصلية)',
  'cloud.compression.medium': 'متوسط (موصى به)',
  'cloud.compression.high': 'عالي (يوفر مساحة)',
  'cloud.sync_status': 'حالة المزامنة',
  'cloud.last_sync': 'آخر مزامنة: {time}',
  'cloud.not_synced': 'لم تتم المزامنة من قبل.',
  'cloud.save_settings': 'حفظ الإعدادات',

  // Delivery
  'delivery.title': 'التوصيل والخدمات اللوجستية',
  'delivery.home_delivery': 'توصيل للمنزل',
  'delivery.pickup': 'الاستلام متاح',
  'delivery.shipping_cost': 'تكلفة الشحن',
  'delivery.estimated_days': 'التسليم المقدر',
  'delivery.days': '{count} أيام',
  'delivery.international_shipping': 'الشحن الدولي متاح',
  'delivery.pickup_instructions': 'تعليمات الاستلام',
  'delivery.create_section_title': 'خيارات التوصيل',
  'delivery.create_home_delivery_label': 'عرض التوصيل للمنزل',
  'delivery.create_pickup_label': 'عرض الاستلام المحلي',
  'delivery.create_cost_placeholder': 'على سبيل المثال، 5.00',
  'delivery.create_days_placeholder': 'على سبيل المثال، 3-5',
  'delivery.create_instructions_placeholder': 'قدم عنوان الاستلام والأوقات المتاحة...',
  'delivery.create_international_label': 'السماح بالشحن الدولي',
  
  // Admin & Moderation
  'moderation.panel_title': 'لوحة الإشراف',
  'moderation.user_panel_title': 'الإشراف على المستخدم',
  'moderation.ad_panel_title': 'الإشراف على الإعلان',
  'moderation.ban_user': 'حظر المستخدم',
  'moderation.unban_user': 'إلغاء حظر المستخدم',
  'moderation.remove_ad': 'إزالة الإعلان',
  'moderation.remove_ad_confirm': 'هل أنت متأكد أنك تريد إزالة هذا الإعلان؟ لا يمكن التراجع عن هذا الإجراء.',
  'moderation.restore_ad': 'استعادة الإعلان',
  'moderation.delete_comment': 'حذف التعليق',
  'moderation.change_tier': 'تغيير فئة المستخدم',
  'moderation.reason_placeholder': 'أدخل سبب الإجراء...',
  'moderation.confirm': 'تأكيد',
  'moderation.banned_user_banner': 'تم حظر هذا المستخدم.',
  'moderation.banned_ad_banner': 'تمت إزالة هذا الإعلان بواسطة مشرف.',
  'moderation.ban_user_confirm': 'هل أنت متأكد أنك تريد حظر {name}؟',
  'moderation.no_reason_provided': 'لم يتم تقديم سبب.',
  'moderation.bulk_action_reason': 'إجراء جماعي.',
  
  // Marketplace Controls
  'controls.filters': 'الفلاتر',
  'controls.sort_by': 'الفرز حسب',
  'controls.sort.relevance': 'الأهمية',
  'controls.sort.date': 'التاريخ',
  'controls.sort.price': 'السعر',
  'controls.sort.popularity': 'الشعبية',
  'controls.sort.date-new-old': 'التاريخ: الأحدث',
  'controls.sort.date-old-new': 'التاريخ: الأقدم',
  'controls.sort.price-low-high': 'السعر: من الأقل إلى الأعلى',
  'controls.sort.price-high-low': 'السعر: من الأعلى إلى الأقل',
  'controls.sort.rating-high-low': 'التقييم: من الأعلى إلى الأقل',
  'controls.sort.rating-low-high': 'التقييم: من الأقل إلى الأعلى',
  'controls.sort.most-liked': 'الشهرة: الأكثر إعجابًا',
  'controls.sort.most-viewed': 'الشهرة: الأكثر مشاهدة',
  'controls.sort.verified-first': 'البائع: الموثق أولاً',
  'controls.sort.nearby-first': 'الموقع: الأقرب أولاً',
  'controls.sort.nearby-first-disabled': 'الأقرب أولاً (مكّن الموقع)',
  'controls.price_range': 'نطاق السعر',
  'controls.categories': 'الفئات',
  'controls.all_categories': 'جميع الفئات',
  'controls.condition': 'الحالة',
  'controls.condition.all': 'الكل',
  'controls.seller_tier': 'فئة البائع',
  'controls.reset_filters': 'إعادة تعيين',
  'controls.view.mode': 'وضع العرض',
  'controls.view.compact': 'مضغوط',
  'controls.view.standard': 'قياسي',
  'controls.view.detailed': 'مفصل',
  'controls.view.list': 'قائمة',
  'controls.results_found_zero': 'لم يتم العثور على نتائج',
  'controls.results_found_one': 'تم العثور على نتيجة واحدة',
  'controls.results_found_two': 'تم العثور على نتيجتين',
  'controls.results_found_few': 'تم العثور على {count} نتائج',
  'controls.results_found_many': 'تم العثور على {count} نتيجة',
  'controls.results_found_other': 'تم العثور على {count} نتيجة',
  'controls.no_results': 'لم يتم العثور على نتائج',
  'controls.no_results_prompt': 'حاول تعديل فلاتر البحث.',
  'controls.close': 'إغلاق',
  'controls.display': 'عرض',
  'controls.actions': 'إجراءات',
  'controls.category_management': 'إدارة الفئات',
  'controls.ad_actions': 'إجراءات الإعلان',
  'controls.add_paid_ad': 'إضافة إعلان مدفوع',
  'controls.social_booster': 'معزز الوسائط الاجتماعية',
  'controls.display_options': 'خيارات العرض',
  'controls.user_section': 'قسم المستخدم',
  'controls.apply_filters': 'تطبيق',
  'controls.manage_categories': 'إدارة',
  'controls.add_category': 'إضافة',
  'controls.add_category_prompt': 'أدخل اسم الفئة الجديدة:',
  'controls.remove_category_confirm': 'هل أنت متأكد أنك تريد إزالة هذه الفئة؟',
  'controls.category_exists_alert': 'الفئة بهذا الاسم موجودة بالفعل.',
  
  // General UI
  'pagination.previous': 'السابق',
  'pagination.next': 'التالي',
  'bottom_nav.explore': 'استكشف',
  'bottom_nav.favorites': 'المفضلة',
  'bottom_nav.messages': 'الرسائل',
  'bottom_nav.profile': 'الملف الشخصي',
  'general.see_more': 'عرض المزيد',
  'general.cancel': 'إلغاء',
  'general.cancel_edit': 'إلغاء التعديل',

  // Translation Controls
  'translation.title': 'الترجمة الفورية',
  'translation.select_language': 'الترجمة إلى:',
  'translation.show_original': 'إظهار الأصل',
  'translation.original_text': '(الأصل: {text})',

  // Login Prompt
  'prompt.join_community.title': 'انضم إلى مجتمعنا!',
  'prompt.join_community.message': 'أنشئ حسابًا لفتح الوصول الكامل والتمتع بجميع مزايا العضوية.',
  'prompt.join_community.benefits_title': 'ستتمكن من:',
  'prompt.join_community.benefit1': 'حفظ إعلاناتك المفضلة',
  'prompt.join_community.benefit2': 'مراسلة البائعين مباشرة',
  'prompt.join_community.benefit3': 'نشر أغراضك الخاصة للبيع',
  'prompt.join_community.confirm': 'تسجيل / تسجيل الدخول',
  'prompt.join_community.cancel': 'ربما لاحقًا',
  
  // FIX: Add missing error boundary translations
  'error.boundary.title': 'حدث خطأ ما',
  'error.boundary.message': 'حدث خطأ غير متوقع. يرجى تحديث الصفحة للمحاولة مرة أخرى.',
  'error.boundary.refresh': 'تحديث الصفحة',

  // Language Settings
  'language_settings.search_placeholder': 'ابحث عن لغة...',
};