export const en = {
  // Header
  appTitle: 'MAZDADY P2P Marketplace',
  createAd: 'Create Ad',

  // Features
  'feature.react_shell.title': 'React + TypeScript App Shell',
  'feature.react_shell.description': 'A robust and scalable application foundation built with React 18, TypeScript, and Vite for a modern development experience.',
  'feature.ui_ux_system.title': 'UI/UX System',
  'feature.ui_ux_system.description': 'A dynamic theming system using CSS variables and Tailwind CSS. Supports both light and dark modes, persisted in local storage.',
  'feature.localization_system.title': 'Localization System (i18n)',
  'feature.localization_system.description': 'A flexible internationalization setup supporting multiple languages (English & Arabic) with RTL text direction.',
  'feature.pwa_config.title': 'PWA Configuration',
  'feature.pwa_config.description': 'Ready for Progressive Web App features. Includes placeholder setup for a service worker and web manifest for offline capabilities.',
  'feature.user_registration.title': 'User Registration & Profile System',
  'feature.user_registration.description': 'Frontend components and state management for user sign-up, login, and session handling.',
  
  // P2P Network Engine Features
  'feature.p2p_node_server.title': 'Lightweight Node Server (Node.js/Rust)',
  'feature.p2p_node_server.description': 'Core P2P node implemented in a high-performance backend (e.g., Node.js or Rust) to handle network connections.',
  'feature.dht_discovery.title': 'DHT Implementation (Discovery Layer)',
  'feature.dht_discovery.description': 'A Distributed Hash Table for peer discovery, allowing nodes to find each other without central servers.',
  'feature.bootstrap_nodes.title': 'Bootstrap Nodes Configuration',
  'feature.bootstrap_nodes.description': 'Initial, stable nodes that new peers connect to in order to join the P2P network.',
  'feature.data_sync.title': 'Data Sync & Conflict Resolution',
  'feature.data_sync.description': 'Mechanisms for synchronizing state across nodes and resolving data conflicts in a distributed environment.',
  'feature.tls_security.title': 'End-to-End TLS Security Layer',
  'feature.tls_security.description': 'Ensuring all peer-to-peer communication is encrypted and secure using Transport Layer Security.',

  // Data & Local Storage System
  'feature.local_database.title': 'Local Database (SQLite/Realm)',
  'feature.local_database.description': 'An embedded, efficient local database for offline data storage and complex query capabilities.',
  'feature.media_management.title': 'Media Management (Images/Videos)',
  'feature.media_management.description': 'System for handling, storing, and retrieving local media files like images and videos efficiently.',
  'feature.metadata_sync.title': 'Metadata Synchronization',
  'feature.metadata_sync.description': 'Ensuring that metadata for local files is kept up-to-date with the P2P network.',
  'feature.cache_management.title': 'Cache Management Strategy',
  'feature.cache_management.description': 'Intelligent caching policies (e.g., LRU) to manage storage and ensure fast access to frequently used data.',
  'feature.media_compression.title': 'Media Compression (WebP/AVIF)',
  'feature.media_compression.description': 'On-the-fly media compression to modern formats like WebP and AVIF to save space and bandwidth.',

  // Main Application UI
  'feature.marketplace.title': 'Marketplace Interface',
  'feature.marketplace.description': 'A fully functional, component-based marketplace UI for browsing and listing items.',
  'feature.search_discovery.title': 'Search & Discovery System',
  'feature.search_discovery.description': 'Advanced search capabilities with filtering, sorting, and a recommendation engine to enhance user discovery.',
  'feature.profile_management.title': 'Profile Management',
  'feature.profile_management.description': 'Comprehensive user profile sections for managing personal information, settings, and public-facing details.',
  'feature.wallet_transactions.title': 'Wallet & Transactions',
  'feature.wallet_transactions.description': 'Secure wallet interface for managing balances, viewing transaction history, and handling payments.',
  'feature.bottom_nav_routing.title': 'Bottom Navigation & Routing',
  'feature.bottom_nav_routing.description': 'An intuitive, mobile-first bottom navigation system with a robust client-side router for seamless page transitions.',

  // Data Transfer & Communication
  'feature.api_integration.title': 'REST/WebSocket APIs',
  'feature.api_integration.description': 'Robust integration with backend services using both RESTful APIs for standard requests and WebSockets for real-time, bidirectional communication.',
  'feature.chunked_transfer.title': 'Chunked Data Transfer',
  'feature.chunked_transfer.description': 'Efficiently handles large file transfers by breaking them into smaller, manageable chunks, with support for pausing and resuming.',
  'feature.lazy_loading.title': 'Lazy Image Loading',
  'feature.lazy_loading.description': 'Improves initial page load performance by deferring the loading of off-screen images until they are needed.',
  'feature.real_time_messaging.title': 'Real-time Messaging',
  'feature.real_time_messaging.description': 'A scalable real-time messaging system for instant communication between users, built on top of WebSockets.',
  'feature.performance_optimization.title': 'Performance Optimization',
  'feature.performance_optimization.description': 'Advanced techniques like code splitting, tree shaking, and request throttling to ensure a fast and responsive user experience.',

  // Offline & Sync System
  'feature.offline_first.title': 'Offline-First Architecture',
  'feature.offline_first.description': 'Designed to work seamlessly offline, ensuring core functionality is always available, with data syncing when a connection is restored.',
  'feature.background_sync.title': 'Background Synchronization',
  'feature.background_sync.description': 'Automatic data synchronization in the background, keeping local and remote data consistent without interrupting the user.',
  'feature.conflict_resolution.title': 'Conflict Resolution (Vector Clocks)',
  'feature.conflict_resolution.description': 'Advanced conflict resolution using vector clocks to merge data changes from different nodes without data loss.',
  'feature.push_notifications.title': 'Push Notifications',
  'feature.push_notifications.description': 'Real-time push notifications to keep users engaged and informed of important updates, even when the app is closed.',
  'feature.local_notifications.title': 'Local Alerts & Notifications',
  'feature.local_notifications.description': 'Schedule and trigger local notifications for reminders, alerts, and time-sensitive events directly on the device.',

  // Testing & Quality Assurance
  'feature.unit_tests.title': 'Unit Tests (Jest)',
  'feature.unit_tests.description': 'Comprehensive unit tests for individual components and functions using Jest and React Testing Library to ensure code reliability.',
  'feature.integration_tests.title': 'Integration Tests (P2P Network)',
  'feature.integration_tests.description': 'Specialized tests to verify the interactions and data flow between different P2P network nodes and system components.',
  'feature.e2e_tests.title': 'E2E Tests (Cypress)',
  'feature.e2e_tests.description': 'End-to-end tests simulating real user scenarios with Cypress to validate the application\'s functionality from the user\'s perspective.',
  'feature.performance_testing.title': 'Performance Testing',
  'feature.performance_testing.description': 'Load and stress testing to measure application responsiveness, scalability, and resource usage under various conditions.',
  'feature.security_auditing.title': 'Security Auditing',
  'feature.security_auditing.description': 'Regular security audits and vulnerability scanning to identify and mitigate potential threats, ensuring data integrity and user privacy.',

  // Deployment & Distribution
  'feature.app_store_deployment.title': 'App Store Deployment',
  'feature.app_store_deployment.description': 'Streamlined process for packaging and deploying the application to the Apple App Store, including metadata and asset management.',
  'feature.play_store_deployment.title': 'Play Store Deployment',
  'feature.play_store_deployment.description': 'Automated build and release pipeline for publishing the application to the Google Play Store for Android devices.',
  'feature.web_pwa.title': 'Web Version (PWA)',
  'feature.web_pwa.description': 'A fully-featured Progressive Web App for instant web access, with offline capabilities and install-to-homescreen functionality.',
  'feature.update_mechanism.title': 'Update Mechanism',
  'feature.update_mechanism.description': 'A seamless, over-the-air update system to deliver new features and bug fixes to users without requiring a full app store update.',
  'feature.analytics_monitoring.title': 'Analytics & Monitoring',
  'feature.analytics_monitoring.description': 'Integration with analytics and performance monitoring tools to track usage, report crashes, and optimize the user experience.',

  // Status
  'status.complete': 'Complete',
  'status.in_progress': 'In Progress',
  'status.active': 'Active',
  'status.banned': 'Banned',

  // ARIA Labels
  'aria.toggle_theme': 'Toggle theme',
  'aria.toggle_language': 'Toggle language',
  'aria.logout': 'Logout',
  'aria.open_admin_panel': 'Open Admin Control Panel',
  'aria.close_admin_panel': 'Close Admin Control Panel',
  'aria.go_back': 'Go Back',
  'aria.open_marketplace_admin_panel': 'Open Marketplace Admin Panel',

  // --- Start of New Auth System Translations ---
  // Auth Page
  'auth.login_title': 'Sign in to MAZDADY',
  'auth.register_title': 'Join MAZDADY',
  'auth.welcome_message': 'The P2P Marketplace',
  'auth.username': 'Username',
  'auth.email': 'Email Address',
  'auth.phone': 'Phone Number',
  'auth.password': 'Password',
  'auth.confirm_password': 'Confirm Password',
  'auth.login_button': 'Sign In',
  'auth.register_button': 'Create Account',
  'auth.go_to_register': "Don't have an account?",
  'auth.go_to_register_link': 'Sign up',
  'auth.go_to_login': 'Already have an account?',
  'auth.go_to_login_link': 'Sign in',
  'auth.welcome_back': 'Welcome back',
  'auth.remember_me': 'Remember me',
  'auth.forgot_password': 'Forgot password?',
  'auth.social_login_divider': 'or continue with',
  'auth.terms_agree': 'I agree to the',
  'auth.terms_and_conditions': 'Terms & Conditions',

  // Social Buttons
  'auth.method.google': 'Sign in with Google',
  'auth.method.facebook': 'Sign in with Facebook',
  'auth.method.twitter': 'Sign in with Twitter',
  'auth.method.apple': 'Sign in with Apple',
  'auth.method.github': 'Sign in with GitHub',
  'auth.method.phone': 'Sign in with Phone',

  // Password Strength
  'auth.password_strength.too_weak': 'Too weak',
  'auth.password_strength.weak': 'Weak',
  'auth.password_strength.medium': 'Medium',
  'auth.password_strength.strong': 'Strong',
  
  // Selectors
  'auth.select_language': 'Select Language',
  'auth.select_country': 'Select Country',

  // Phone Verification
  'auth.phone_verification_title': 'Verify Your Phone Number',
  'auth.enter_phone_prompt': 'Enter your phone number to receive a verification code.',
  'auth.send_code': 'Send Code',
  'auth.enter_code_prompt': 'Enter the 6-digit code we sent to your phone.',
  'auth.verification_code': 'Verification Code',
  'auth.verify': 'Verify',
  'auth.resend_code': 'Resend Code',
  'auth.back_to_login': 'Back to login',
  'auth.error_invalid_code': 'Invalid verification code.',
  
  // 2FA Verification
  'auth.2fa_title': 'Two-Factor Authentication',
  'auth.2fa_prompt': 'A verification code has been sent to your authentication app.',
  'auth.2fa_enter_code': 'Enter 6-digit code',

  // OAuth Handler
  'auth.oauth_redirect_title': 'Connecting...',
  'auth.oauth_redirect_message': 'Redirecting you to {provider} for authentication. Please wait.',
  'auth.connecting_to': 'Connecting to {provider}...',
  'auth.error_oauth_failed': 'Failed to connect with {provider}. Please try again.',
  'auth.try_again': 'Try Again',

  // Errors
  'auth.error_invalid_credentials': 'Invalid email or password.',
  'auth.error_generic': 'An unexpected error occurred. Please try again.',
  'auth.error_user_exists': 'A user with this email already exists.',
  'auth.error_password_mismatch': "Passwords do not match.",
  'auth.error_invalid_email': 'Please enter a valid email address.',
  'auth.error_username_short': 'Username must be at least 3 characters.',
  'auth.error_phone_invalid': 'Please enter a valid phone number.',
  'auth.error_terms_required': 'You must accept the terms and conditions.',
  'auth.error_field_required': 'This field is required.',
  'auth.error_account_locked': 'Too many failed login attempts. Your account is locked for 60 seconds.',
  'auth.error_session_expired': 'Your session has expired. Please log in again.',

  // Admin Panel
  'admin.title': 'Admin Controls',
  'admin.enabled_methods': 'Enabled Login Methods',
  'admin.visible_elements': 'Visible UI Elements',
  'admin.color_scheme': 'Color Scheme',
  'admin.primary': 'Primary',
  'admin.background': 'Background',
  'admin.text': 'Text',
  'admin.button': 'Button',
  'admin.button_text': 'Button Text',
  'admin.border': 'Border',
  'admin.custom_css': 'Custom CSS',
  'admin.dashboard_title': 'Admin Dashboard',
  'admin.user_tiers_config': 'User Tiers',
  'admin.tier_benefits': 'Benefits',
  'admin.tier_requirements': 'Requirements',
  'admin.max_ads': 'Max Ads',
  'admin.image_slots': 'Image Slots',
  'admin.min_transactions': 'Min Transactions',
  'admin.min_rating': 'Min Rating',
  'admin.save_changes': 'Save Changes',
  'admin.user_management': 'User Management',
  'admin.ad_management': 'Ad Management',
  'admin.moderation_queue': 'Moderation Queue',
  'admin.activity_log': 'Activity Log',
  'admin.system_config': 'System Config',
  'admin.search_users': 'Search users by name or email...',
  'admin.search_ads': 'Search ads by title...',
  'admin.user': 'User',
  'admin.status': 'Status',
  'admin.tier': 'Tier',
  'admin.ip_address': 'IP Address',
  'admin.actions': 'Actions',
  'admin.ad_title': 'Ad Title',
  'admin.seller': 'Seller',
  'admin.reports': 'Reports',
  'admin.reason': 'Reason(s)',
  'admin.approve': 'Approve',
  'admin.remove': 'Remove',
  'admin.select_all': 'Select All',
  'admin.bulk_actions': 'Bulk Actions',
  'admin.ban_selected': 'Ban Selected',
  'admin.unban_selected': 'Unban Selected',
  'admin.remove_selected': 'Remove Selected',
  'admin.log_event': 'Event',
  'admin.log_details': 'Details',
  'admin.log_timestamp': 'Timestamp',
  'admin.log.user_registered': 'User Registered',
  'admin.log.ad_posted': 'Ad Posted',
  'admin.log.user_login': 'User Logged In',
  'admin.config.site_maintenance': 'Site Maintenance',
  'admin.config.maintenance_enabled': 'Enable Maintenance Mode',
  'admin.config.registration_open': 'User Registration',
  'admin.config.registration_enabled': 'Allow New Registrations',
  'admin.config.commission_rates': 'Commission Rates (%)',
  'admin.config.content_moderation': 'Content Moderation Strategy',
  'admin.config.moderation.auto': 'Automatic',
  'admin.config.moderation.manual': 'Manual',
  'admin.config.moderation.hybrid': 'Hybrid',
  'admin.config.payment_methods': 'Enabled Payment Methods',
  'admin.config.payment.credit_card': 'Credit Card',
  'admin.config.payment.paypal': 'PayPal',
  'admin.config.payment.crypto': 'Crypto',
  'admin.config.payment.bank_transfer': 'Bank Transfer',
  
  // Marketplace
  'marketplace.title': 'Explore Listings',
  'marketplace.search_placeholder': 'Search for anything...',
  'ad.posted_by': 'Posted by',
  'ad.seller_info': "Seller Information",
  'ad.details': 'Details',
  'ad.condition': 'Condition',
  'ad.quantity': 'Quantity',
  'ad.category': 'Category',
  'ad.location': 'Location',
  'ad.description': 'Description',
  'ad.specifications': 'Specifications',
  'ad.delivery_info': 'Delivery Information',
  'ad.delivery_type': 'Delivery Type',
  'ad.delivery_time': 'Est. Delivery Time',
  'ad.delivery_cost': 'Delivery Cost',
  'ad.video_preview': 'Video Preview',
  'ad.document_preview': 'Document Preview',
  
  // Ad Creation
  'ad.create.title': 'Create a New Ad',
  'ad.create.step1': 'Details',
  'ad.create.step2': 'Media',
  'ad.create.step3': 'Delivery',
  'ad.create.step4': 'Review',
  'ad.create.next_step': 'Next Step',
  'ad.create.prev_step': 'Previous Step',
  'ad.create.post_ad': 'Post Ad',
  'ad.create.title_label': 'Ad Title',
  'ad.create.description_label': 'Description',
  'ad.create.price_label': 'Price',
  'ad.create.category_label': 'Category',
  'ad.create.condition_label': 'Condition',
  'ad.create.quantity_label': 'Quantity',
  'ad.create.condition_new': 'New',
  'ad.create.condition_used': 'Used',
  'ad.create.condition_refurbished': 'Refurbished',
  'ad.create.image_upload_label': 'Upload Images (WebP, 85% quality)',
  'ad.create.image_upload_prompt': 'Click to upload your ad image',
  'ad.create.image_compressing': 'Compressing image...',
  'ad.create.original_size': 'Original',
  'ad.create.compressed_size': 'Compressed',
  'ad.create.size_reduction': 'Reduction',
  'ad.create.video_upload_label': 'Upload Video (Optional)',
  'ad.create.video_upload_prompt': 'Max 60s, compressed to 720p',
  'ad.create.video_trim_warning': 'Video is longer than 60s and will be trimmed.',
  'ad.create.video_compressing': 'Simulating video compression...',
  'ad.create.document_upload_label': 'Upload Document (PDF, Optional)',
  'ad.create.document_upload_prompt': 'e.g., manual, syllabus',
  'ad.create.pdf_conversion_info': 'PDF will be converted to a streamable, fast-preview format.',
  'ad.create.review_title': 'Review Your Ad',
  'ad.create.limit_reached_title': 'Ad Limit Reached',
  'ad.create.limit_reached_message': 'You have posted {adCount} of {limit} ads allowed for your {tier} tier.',
  'ad.create.limit_reached_suggestion': 'To post more ads, please upgrade your account tier.',
  'ad.create.back_to_marketplace': 'Back to Marketplace',

  // Social
  'social.like': 'Like',
  'social.save': 'Save',
  'social.share': 'Share',
  'social.comments_section': 'Comments',
  'social.reviews_section': 'Ratings & Reviews',
  'social.add_comment_placeholder': 'Add a comment...',
  'social.add_comment_button': 'Post',
  'social.no_comments': 'No comments yet.',
  'social.no_reviews': 'No reviews yet.',
  'social.rate_this_ad': 'Rate this item',
  'social.your_rating': 'Your Rating',
  'social.your_review': 'Your Review',
  'social.submit_review': 'Submit Review',
  'social.reply': 'Reply',

  // Profile
  'profile.title': 'Profile',
  'profile.settings': 'Settings',
  'profile.cloud_sync_title': 'Cloud Sync Settings',
  'profile.member_since': 'Member Since',
  'profile.bio': 'Bio',
  'profile.reputation': 'Reputation',
  'profile.overall_rating': 'Overall Rating',
  'profile.reviews': 'Reviews',
  'profile.active_ads': 'Active Ads',
  'profile.my_ads': 'My Ads',
  'profile.verified': 'Verified',

  // Cloud Sync
  'cloud.connect_provider': 'Connect Cloud Storage',
  'cloud.provider.google-drive': 'Connect Google Drive',
  'cloud.provider.dropbox': 'Connect Dropbox',
  'cloud.connected_as': 'Connected as {email}',
  'cloud.disconnect': 'Disconnect',
  'cloud.settings': 'Sync Settings',
  'cloud.enable_sync': 'Enable Auto-Sync',
  'cloud.wifi_only': 'Sync on Wi-Fi only',
  'cloud.media_compression': 'Media Compression',
  'cloud.compression.none': 'None (Original Quality)',
  'cloud.compression.medium': 'Medium (Recommended)',
  'cloud.compression.high': 'High (Saves Space)',
  'cloud.sync_status': 'Sync Status',
  'cloud.last_sync': 'Last synced: {time}',
  'cloud.not_synced': 'Never synced.',
  'cloud.save_settings': 'Save Settings',

  // Delivery
  'delivery.title': 'Delivery & Logistics',
  'delivery.home_delivery': 'Home Delivery',
  'delivery.pickup': 'Pickup Available',
  'delivery.shipping_cost': 'Shipping Cost',
  'delivery.estimated_days': 'Estimated Delivery',
  'delivery.days': '{count} days',
  'delivery.international_shipping': 'International Shipping Available',
  'delivery.pickup_instructions': 'Pickup Instructions',
  'delivery.create_section_title': 'Delivery Options',
  'delivery.create_home_delivery_label': 'Offer Home Delivery',
  'delivery.create_pickup_label': 'Offer Local Pickup',
  'delivery.create_cost_placeholder': 'e.g., 5.00',
  'delivery.create_days_placeholder': 'e.g., 3-5',
  'delivery.create_instructions_placeholder': 'Provide pickup address and available times...',
  'delivery.create_international_label': 'Allow International Shipping',
  
  // Admin & Moderation
  'moderation.panel_title': 'Moderation Panel',
  'moderation.user_panel_title': 'User Moderation',
  'moderation.ad_panel_title': 'Ad Moderation',
  'moderation.ban_user': 'Ban User',
  'moderation.unban_user': 'Unban User',
  'moderation.remove_ad': 'Remove Ad',
  'moderation.restore_ad': 'Restore Ad',
  'moderation.delete_comment': 'Delete Comment',
  'moderation.change_tier': 'Change User Tier',
  'moderation.reason_placeholder': 'Enter reason for moderation...',
  'moderation.confirm': 'Confirm',
  'moderation.banned_user_banner': 'This user has been banned.',
  'moderation.banned_ad_banner': 'This ad has been removed by a moderator.',
  
  // Marketplace Controls
  'controls.filters': 'Filters',
  'controls.sort_by': 'Sort By',
  'controls.sort.date-new-old': 'Date: Newest',
  'controls.sort.date-old-new': 'Date: Oldest',
  'controls.sort.price-low-high': 'Price: Low to High',
  'controls.sort.price-high-low': 'Price: High to Low',
  'controls.sort.rating-high-low': 'Rating: High to Low',
  'controls.sort.rating-low-high': 'Rating: Low to High',
  'controls.sort.most-liked': 'Popularity: Most Liked',
  'controls.sort.most-viewed': 'Popularity: Most Viewed',
  'controls.sort.verified-first': 'Seller: Verified First',
  'controls.sort.nearby-first': 'Location: Nearby First',
  'controls.sort.nearby-first-disabled': 'Nearby First (Enable Location)',
  'controls.price_range': 'Price Range',
  'controls.categories': 'Categories',
  'controls.condition': 'Condition',
  'controls.condition.all': 'All',
  'controls.seller_tier': 'Seller Tier',
  'controls.reset_filters': 'Reset',
  'controls.view.mode': 'View Mode',
  'controls.view.compact': 'Compact',
  'controls.view.standard': 'Standard',
  'controls.view.detailed': 'Detailed',
  'controls.view.list': 'List',
  'controls.results_found': '{count} results found',

  // Translation Controls
  'translation.title': 'Real-time Translation',
  'translation.select_language': 'Translate to:',
  'translation.show_original': 'Show Original',
};